# Generated by Django 5.1.15 on 2026-08-26 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='is_cross_level',
            field=models.BooleanField(default=False, help_text='True if assigned across hierarchy requiring parent chain approvals'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('ASSIGNED', 'Assigned'), ('PENDING_APPROVAL', 'Pending Parent Approval'), ('IN_PROGRESS', 'In Progress'), ('SUBMITTED', 'Submitted for Review'), ('UNDER_REVIEW', 'Under Review'), ('CHANGES_REQUESTED', 'Changes Requested'), ('APPROVED', 'Approved'), ('COMPLETED', 'Completed'), ('REJECTED', 'Delegation Rejected'), ('OVERDUE', 'Overdue')], db_index=True, default='ASSIGNED', max_length=30),
        ),
    ]
