# Generated by Django 5.1.15 on 2026-08-26 04:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='taskapproval',
            name='approval_tier',
            field=models.PositiveIntegerField(default=1, help_text='Tier in approval hierarchy (1=Immediate Parent, 2=Grandparent / L1)'),
        ),
        migrations.AddField(
            model_name='taskapproval',
            name='approval_type',
            field=models.CharField(choices=[('TASK_COMPLETION', 'Task Completion Review'), ('CROSS_LEVEL_DELEGATION', 'Cross-Level Task Delegation')], db_index=True, default='TASK_COMPLETION', max_length=40),
        ),
        migrations.AlterField(
            model_name='taskapproval',
            name='reviewer',
            field=models.ForeignKey(help_text='The supervisor/manager reviewing this request', on_delete=django.db.models.deletion.CASCADE, related_name='conducted_reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='taskapproval',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved'), ('CHANGES_REQUESTED', 'Changes Requested'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=30),
        ),
        migrations.AlterField(
            model_name='taskapproval',
            name='submitted_by',
            field=models.ForeignKey(help_text='The user who submitted this task or initiated delegation', on_delete=django.db.models.deletion.CASCADE, related_name='submitted_approvals', to=settings.AUTH_USER_MODEL),
        ),
    ]
